### ISSUE TITLE
bunch of errors when executing long python script in interactive console

### ISSUE THREAD

**Issue by ctech4285** [UAVCAN/gui_tool#1]
This script below runs for some time when done endless amount of errors get reported. Log file attached 
uavcan_gui_tool --debug 

[uavcan_gui_tool-l3pfzp1k.log.txt](https://github.com/UAVCAN/gui_tool/files/348542/uavcan_gui_tool-l3pfzp1k.log.txt)

```
i = 470
t = -1
c = 0
while (i > 20):
	i = i*0.99
	
	
	if (t == -1):
		c = 1000 + int(i)
	if (t == 1):
		c = int(i)
	
	t = t* -1
	print ("command", c)
	broadcast(uavcan.equipment.hardpoint.Command(hardpoint_id=1, command=c))	
	time.sleep(0.3);
```

**Comment by pavel-kirienko** [comment]
I hate to say this, but this is the expected behavior. The IPython kernel is executed in the main thread, so if your script blocks it for a significant amount of time, you will get all kinds of weird and wonderful glitches.

There are two solutions:

* Move the IPython kernel into a separate process or thread. This involves much refactoring and hair pulling, so I'm not planning to do that anytime soon (however, a pull request is always welcome).

* Use only asynchronous code. Seeing as you come from procedural background, it may require some getting used to. Your code can be refactored into async alternative roughly as follows (I didn't have a chance to test it) (there is also about one million other ways to do this):

```python
i = 470
t = -1

def run_once():
    global i, t
    i *= 0.99
    c = int(i) + (1000 if t < 0 else 0)
    t = -t
    print('command', c)
    broadcast(uavcan.equipment.hardpoint.Command(hardpoint_id=1, command=c))
    if i > 20:
        node.defer(0.3, run_once)

node.defer(0, run_once)
```

**Comment by pavel-kirienko** [comment]
http://uavcan.org/GUI_Tool/User_guide/#programming-tips
