### ISSUE TITLE
Not compatible with KDE Breeze dark theme

### ISSUE THREAD

**Issue by Mebus** [UAVCAN/gui_tool#41]
The GUI is not compatible with the KDE Breeze Dark Theme of KDE, i.e. I cannot read the values in the monitor:

![grafik](https://user-images.githubusercontent.com/271557/73125927-ce857900-3fac-11ea-8525-5caff5e3e5f3.png)

Also the buttons have almost got no contrast.

Would be nice, if you could fix this.

Mebus

**Comment by coderkalyan** [comment]
@Mebus I am closing this because:
1. The UAVCAN gui_tool is legacy as it only applies to V0. As such, I am only providing limited maintenance from now on. For V1, please take a look at [Yakut](https://github.com/UAVCAN/yakut) (CLI tool, completed) and [Yukon](https://github.com/uavcan/yukon) (next generation GUI tool, not yet completed).
2. I have very limited bandwidth at the moment to dedicate to non-essential tickets.
3. It's been open for a very long time.

Now that said: if you are willing to send a PR fixing this issue, I will be happy to take a look at it and merge!
